export const mockLocations = [
  {
    id: 'mega-concept',
    name: 'MEGA CONCEPT',
    slug: 'mega-concept',
    logo: '/logos/megakoncept.png',
    shortDescription: 'Organizacija Dana italijanskog dizajna je 21. maja 2026.',
    longDescription:
      'Organizacija Dana italijanskog dizajna u njihovom prostoru je 21.05.2026. Učešće na poziv. Da biste dobili poziv, pošaljite e-mail na: office@megaconcept.rs',
    address: 'Omladinskih brigada 86ž, Novi Beograd – West 65',
    email: 'office@megaconcept.rs',
    phone: null,
    website: 'https://www.megaconcept.rs',
    coordinates: { lat: 44.8127, lon: 20.4020 },
    schedule: null,
    order: 1,
  },
  {
    id: 'novo-lux',
    name: 'NOVO LUX',
    slug: 'novo-lux',
    logo: '/logos/novolux.png',
    shortDescription: 'Organizacija Dana italijanskog dizajna je 20. maja 2026.',
    longDescription:
      'Organizacija Dana italijanskog dizajna u njihovom prostoru je 20.05.2026. Učešće na poziv. Da biste dobili poziv, pošaljite e-mail na: office@novolux.rs',
    address: 'Grčića Milenka 83, Beograd',
    email: 'office@novolux.rs',
    phone: null,
    website: 'https://www.novolux.rs',
    coordinates: { lat: 44.7832, lon: 20.4850 },
    schedule: null,
    order: 2,
  },
  {
    id: 'nitea',
    name: 'NITEA',
    slug: 'nitea',
    logo: '/logos/nitea.png',
    shortDescription: 'Organizacija Dana italijanskog dizajna je 14. maja 2026.',
    longDescription:
      'Organizacija Dana italijanskog dizajna u njihovom prostoru je 14.05.2026. Učešće na poziv. Da biste dobili poziv, pošaljite e-mail na: home@nitea.rs',
    address: 'Đušina 8, Beograd',
    email: 'home@nitea.rs',
    phone: null,
    website: 'https://www.nitea.rs',
    coordinates: { lat: 44.8218, lon: 20.4672 },
    schedule: null,
    order: 3,
  },
  {
    id: 'alba-dominante',
    name: 'ALBA DOMINANTE',
    slug: 'alba-dominante',
    logo: '/logos/albadominante.png',
    shortDescription: 'Organizacija Dana italijanskog dizajna je 12. maja 2026.',
    longDescription:
      'Organizacija Dana italijanskog dizajna u njihovom prostoru je 12.05.2026. Učešće na poziv. Da biste dobili poziv, pošaljite e-mail na: home@albadominante.com',
    address: 'Milutina Milankovića 1/a, Novi Beograd',
    email: 'home@albadominante.com',
    phone: null,
    website: 'https://www.albadominante.com',
    coordinates: { lat: 44.8090, lon: 20.4240 },
    schedule: null,
    order: 4,
  },
  {
    id: 'artefacto',
    name: 'ARTEFACTO',
    slug: 'artefacto',
    logo: '/logos/artefacto.png',
    shortDescription: 'Organizacija Dana italijanskog dizajna je 14. maja 2026.',
    longDescription:
      'Organizacija Dana italijanskog dizajna u njihovom prostoru je 14.05.2026. Učešće na poziv. Da biste dobili poziv, pošaljite e-mail na: info@artefacto.rs',
    address: 'Svetogorska 39, Beograd',
    email: 'info@artefacto.rs',
    phone: null,
    website: 'https://www.artefacto.rs',
    coordinates: { lat: 44.8145, lon: 20.4615 },
    schedule: null,
    order: 5,
  },
  {
    id: 'workshop-mapei-kolarac',
    name: 'Workshop Mapei & Kolarac',
    slug: 'workshop-mapei-kolarac',
    logo: ['/logos/mapei.png', '/logos/kolarac.png'],
    shortDescription: 'Organizacija Dana italijanskog dizajna je 12. maja 2026.',
    longDescription:
      '„Italijanski materijali i tehnologije za regeneraciju i valorizaciju kulturnog i istorijskog nasleđa" — Organizacija Dana italijanskog dizajna u njihovom prostoru je 12.05.2026. Učešće na poziv.',
    address: 'Galerija Fondacije Ilija M. Kolarac, Studentski trg 5, Beograd',
    email: null,
    phone: null,
    website: null,
    coordinates: { lat: 44.8187, lon: 20.4590 },
    schedule: null,
    order: 6,
  },
];
