export const mockLocations = [
  {
    id: 'forma-milano',
    name: 'Forma Milano',
    slug: 'forma-milano',
    logo: null,
    shortDescription: 'Savremeni italijanski nameštaj i dekoracija enterijera.',
    longDescription: 'Forma Milano predstavlja vodeće italijanske brendove nameštaja i unutrašnje dekoracije. Specijalizovani smo za dizajnerske komade koji spajaju funkcionalnost i estetiku. Posetite naš showroom i pronađite inspiraciju za vaš dom.',
    address: 'Knez Mihailova 20, 11000 Beograd',
    email: 'info@formamilano.rs',
    phone: '+381 11 3281 200',
    website: 'https://formamilano.rs',
    coordinates: { lat: 44.8185, lon: 20.4573 },
    schedule: {
      days: [
        { date: '2026-05-15', open: '10:00', close: '20:00' },
        { date: '2026-05-16', open: '11:00', close: '19:00' },
      ],
    },
    order: 1,
  },
  {
    id: 'casa-italiana',
    name: 'Casa Italiana',
    slug: 'casa-italiana',
    logo: null,
    shortDescription: 'Ekskluzivni enterijer i dizajnerski dodaci iz Italije.',
    longDescription: 'Casa Italiana donosi duh mediteranskog stila direktno u Beograd. Naša kolekcija obuhvata sve od luksuznih sofa do unikatnih svetiljki i tepiha. Naši stručnjaci za dizajn enterijera su tu da vam pomognu da stvorite savršen prostor.',
    address: 'Terazije 5, 11000 Beograd',
    email: 'kontakt@casaitaliana.rs',
    phone: '+381 11 3243 101',
    website: null,
    coordinates: { lat: 44.8165, lon: 20.4622 },
    schedule: {
      days: [
        { date: '2026-05-15', open: '10:00', close: '19:00' },
        { date: '2026-05-16', open: '12:00', close: '20:00' },
      ],
    },
    order: 2,
  },
  {
    id: 'novolux-design',
    name: 'Novolux Design',
    slug: 'novolux-design',
    logo: null,
    shortDescription: 'Rasveta i dekorativni elementi vrhunskog kvaliteta.',
    longDescription: 'Novolux Design je specijalizovana prodavnica rasvete i dekorativnih elemenata koji transformišu svaki prostor. Iz naše kolekcije biraju arhitekte, dizajneri i zahtevni kupci koji traže jedinstven vizuelni identitet svog doma ili poslovnog prostora.',
    address: 'Bulevar Kralja Aleksandra 48, 11000 Beograd',
    email: 'info@novolux.rs',
    phone: '+381 11 3440 855',
    website: 'https://novolux.rs',
    coordinates: { lat: 44.8156, lon: 20.4699 },
    schedule: {
      days: [
        { date: '2026-05-15', open: '09:00', close: '18:00' },
        { date: '2026-05-16', open: '10:00', close: '18:00' },
      ],
    },
    order: 3,
  },
  {
    id: 'studio-interno',
    name: 'Studio Interno',
    slug: 'studio-interno',
    logo: null,
    shortDescription: 'Autorski nameštaj i predmeti savremenog dizajna.',
    longDescription: 'Studio Interno je boutique galerija koja promoviše autorski pristup dizajnu nameštaja. Svaki komad u našoj ponudi je rezultat saradnje sa talentovanim dizajnerima iz Italije i Srbije. Posetite nas i otkrijte predmete koji pričaju priču.',
    address: 'Skadarska 32, 11000 Beograd',
    email: 'studio@interno.rs',
    phone: null,
    website: 'https://studiointerno.rs',
    coordinates: { lat: 44.8198, lon: 20.4629 },
    schedule: {
      days: [
        { date: '2026-05-15', open: '11:00', close: '21:00' },
        { date: '2026-05-16', open: '11:00', close: '21:00' },
      ],
    },
    order: 4,
  },
  {
    id: 'artefacto-beograd',
    name: 'Artefacto Beograd',
    slug: 'artefacto-beograd',
    logo: null,
    shortDescription: 'Galerija umetničkih predmeta i dizajnerskog nameštaja.',
    longDescription: 'Artefacto Beograd spaja svet umetnosti i funkcionalnog dizajna. Naša galerija predstavlja pažljivo odabrane predmete koji se nalaze na granici između dekoracije i umetničkog dela. Idealno mesto za poklon ili za opremanje posebnog prostora.',
    address: 'Karađorđeva 2, 11000 Beograd',
    email: 'beograd@artefacto.rs',
    phone: '+381 11 2631 044',
    website: null,
    coordinates: { lat: 44.8093, lon: 20.4467 },
    schedule: {
      days: [
        { date: '2026-05-15', open: '10:00', close: '20:00' },
        { date: '2026-05-16', open: '10:00', close: '20:00' },
      ],
    },
    order: 5,
  },
  {
    id: 'spazio-design',
    name: 'Spazio Design',
    slug: 'spazio-design',
    logo: null,
    shortDescription: 'Kompletno opremanje prostora u italijanskom stilu.',
    longDescription: 'Spazio Design nudi kompletan servis dizajna enterijera, od prve konsultacije do finalne realizacije. Naš tim arhitekata i dizajnera specijalizovan je za projekte u mediteranskom i savremenom italijanskom stilu, za stambene i poslovne prostore.',
    address: 'Nemanjina 14, 11000 Beograd',
    email: 'hello@spaziodesign.rs',
    phone: '+381 11 3613 072',
    website: 'https://spaziodesign.rs',
    coordinates: { lat: 44.8074, lon: 20.4626 },
    schedule: {
      days: [
        { date: '2026-05-15', open: '10:00', close: '18:00' },
        { date: '2026-05-16', open: '12:00', close: '20:00' },
      ],
    },
    order: 6,
  },
];
